import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {buildValidationEnvironment,inferValidationCommands,runAcceptance} from '../core/acceptance.mjs';import {shellInvocation} from '../core/terminal.mjs';
test('infers package check plus adjacent validation scripts and executes a passing hard gate',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({scripts:{check:"node -e \"process.exit(0)\"",test:"node -e \"process.exit(0)\"",lint:"node -e \"process.exit(0)\""}}));assert.deepEqual(inferValidationCommands(root),['npm run check','npm run test','npm run lint']);const result=await runAcceptance(root,null,{mode:'workspace'});assert.equal(result.passed,true);assert.equal(result.results.length,3);assert.equal(result.hardGate,'PASS')});
test('stops on first failed validation command',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-'));const result=await runAcceptance(root,['node -e "process.exit(2)"','node -e "process.exit(0)"'],{mode:'workspace'});assert.equal(result.passed,false);assert.equal(result.results.length,1)});
test('validation environment keeps execution basics but drops undeclared parent values',()=>{const env=buildValidationEnvironment({PATH:'/bin',HOME:'/tmp/home',LANG:'C.UTF-8',LC_TEST:'x',TAOWIND_VALIDATION_SECRET:'classified',GITHUB_TOKEN:'token'});assert.equal(env.PATH,'/bin');assert.equal(env.HOME,'/tmp/home');assert.equal(env.LANG,'C.UTF-8');assert.equal(env.LC_TEST,'x');assert.equal(env.TAOWIND_VALIDATION_SECRET,undefined);assert.equal(env.GITHUB_TOKEN,undefined)});
test('validation commands do not inherit parent secrets',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-'));const key='TAOWIND_VALIDATION_SECRET';const prev=process.env[key];process.env[key]='classified-value';try{const result=await runAcceptance(root,[`node -e "process.stdout.write(process.env.${key}||'missing')"`],{mode:'workspace'});assert.equal(result.passed,true);assert.equal(result.results[0].stdout,'missing');}finally{if(prev===undefined)delete process.env[key];else process.env[key]=prev;}});
test('isolated validation shell bypasses POSIX login/profile startup',()=>{const spec=shellInvocation('node --version',{platform:'linux',isolatedShell:true});assert.equal(spec.shell,'/bin/bash');assert.deepEqual(spec.args.slice(0,3),['--noprofile','--norc','-c']);assert.equal(spec.args[3],'node --version')});
test('acceptance fails closed when validation exceeds its output budget',{skip:process.platform==='win32'},async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-output-'));const script="process.stdout.write('x'.repeat(500000));setTimeout(()=>{},5000)";const started=Date.now();const result=await runAcceptance(root,[`node -e ${JSON.stringify(script)}`],{mode:'workspace'});assert.equal(result.passed,false);assert.equal(result.hardGate,'COMMAND_FAILED');assert.equal(result.results[0].outputLimitExceeded,true);assert.ok(result.results[0].stdout.length<=240000);assert.ok(Date.now()-started<2000,`acceptance output limit took ${Date.now()-started}ms`)});

test('inferred validation does not let a passing check mask a failing test',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({scripts:{check:"node -e \"process.exit(0)\"",test:"node -e \"process.exit(3)\""}}));const result=await runAcceptance(root,null,{mode:'workspace'});assert.equal(result.passed,false);assert.deepEqual(result.commands,['npm run check','npm run test']);assert.equal(result.results.length,2);assert.equal(result.results[0].code,0);assert.equal(result.results[1].code,3);assert.equal(result.hardGate,'COMMAND_FAILED')});

test('mixed-language inference does not let package validation mask failing pytest',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-acc-mixed-'));fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({scripts:{check:"node -e \"process.exit(0)\""}}));fs.writeFileSync(path.join(root,'pyproject.toml'),'[tool.pytest.ini_options]\n');fs.writeFileSync(path.join(root,'test_failure.py'),'def test_failure():\n    assert False\n');assert.deepEqual(inferValidationCommands(root),['npm run check','python -m pytest -q']);const result=await runAcceptance(root,null,{mode:'workspace'});assert.equal(result.passed,false);assert.deepEqual(result.commands,['npm run check','python -m pytest -q']);assert.equal(result.results.length,2);assert.equal(result.results[0].code,0);assert.notEqual(result.results[1].code,0);assert.equal(result.hardGate,'COMMAND_FAILED')});
