import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {AutonomousGoalSupervisor} from '../core/autonomous-supervisor.mjs';
class FakeRunner{
  constructor(){this.runs=new Map();this.n=0}
  create(goal){const r={id:`run-${++this.n}`,goal,status:'PLANNED',mode:'WHOLE_ARTIFACT',dwac:{connected:true,status:'COMPILED',mode:'WHOLE_ARTIFACT'},evidence:[],validation:null,delivery:null};this.runs.set(r.id,r);return structuredClone(r)}
  get(id){return structuredClone(this.runs.get(id))}
  async synthesize(id){const r=this.runs.get(id);r.status='CHANGESET_STAGED';return this.get(id)}
  apply(id){const r=this.runs.get(id);r.status='CHANGES_APPLIED';return {run:this.get(id)}}
  async validate(id){const r=this.runs.get(id);r.status='READY_FOR_DELIVERY';r.validation={passed:true,status:'PASSED'};r.evidence.push({kind:'validation'});return this.get(id)}
  async repair(id){return this.get(id)}
  delivery(id){const r=this.runs.get(id);r.delivery={head:'abc',pushPerformed:false};r.evidence.push({kind:'git-delivery'});return this.get(id)}
}
function fixture(assess){const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'twc-mission-'));const runner=new FakeRunner();return {runtime,runner,supervisor:new AutonomousGoalSupervisor({runner,runtimeDir:runtime,assessGoal:assess,contextProvider:()=>({stats:{files:9}})})}}
test('autonomous mission closes only after validated run and closure audit',async()=>{const f=fixture(async()=>({closed:true,confidence:.93,gaps:[],next_goal:'',recommended_mode:'WHOLE_ARTIFACT'}));const m=f.supervisor.start('ship verified feature');const out=await f.supervisor.tick(m.id);assert.equal(out.status,'GOAL_CLOSED');assert.equal(out.cycle,1);assert.equal(out.cycles.length,1);assert.equal(out.evidence.at(-1).kind,'goal-closure-assessment')});
test('mission recompiles a new cycle when auditors find a gap',async()=>{let n=0;const f=fixture(async()=>++n===1?{closed:false,confidence:.91,gaps:[{id:'g1',problem:'add regression coverage',severity:.9}],next_goal:'add regression coverage',recommended_mode:'DEEP_DEVELOPMENT'}:{closed:true,confidence:.95,gaps:[],next_goal:'',recommended_mode:'WHOLE_ARTIFACT'});const m=f.supervisor.start('complete product',{maxCycles:4});const a=await f.supervisor.tick(m.id);assert.equal(a.status,'ACTIVE');assert.equal(a.cycle,1);assert.equal(a.nextGoal,'add regression coverage');assert.equal(a.currentRunId,null);const b=await f.supervisor.tick(m.id);assert.equal(b.status,'GOAL_CLOSED');assert.equal(b.cycle,2);assert.equal(b.cycles.length,2)});
test('mission stops fail-closed when cycle budget is exhausted',async()=>{const f=fixture(async()=>({closed:false,confidence:.88,gaps:[{id:'g',problem:'still open',severity:1}],next_goal:'still open',recommended_mode:'DEEP_DEVELOPMENT'}));const m=f.supervisor.start('hard goal',{maxCycles:2});const out=await f.supervisor.run(m.id,{maxTicks:8});assert.equal(out.status,'BUDGET_EXHAUSTED');assert.equal(out.cycle,2)});
test('read-only mission pauses before applying generated changes',async()=>{const f=fixture(async()=>({closed:true,confidence:1,gaps:[],next_goal:''}));const m=f.supervisor.start('change code');const out=await f.supervisor.tick(m.id,{approvalMode:'read_only'});assert.equal(out.status,'WAITING_APPROVAL');assert.match(out.blocker,/Read only/)});
test('mission state survives supervisor reconstruction',async()=>{const f=fixture(async()=>({closed:false,confidence:.8,gaps:[],next_goal:'continue',recommended_mode:'WHOLE_ARTIFACT'}));const m=f.supervisor.start('persistent goal');await f.supervisor.tick(m.id);const next=new AutonomousGoalSupervisor({runner:f.runner,runtimeDir:f.runtime,assessGoal:async()=>({closed:true,confidence:1,gaps:[],next_goal:''})});assert.equal(next.get(m.id).cycle,1);assert.equal(next.get(m.id).status,'ACTIVE')});
