import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {ChangesetStore} from '../core/changesets.mjs';
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'twc-cs-')),workspace=path.join(base,'repo'),runtime=path.join(base,'runtime');fs.mkdirSync(workspace);fs.writeFileSync(path.join(workspace,'a.txt'),'old\n');return {base,workspace,runtime}}
function replaceSame(file,content){const tmp=`${file}.replacement-${process.pid}-${Date.now()}`;fs.writeFileSync(tmp,content);fs.renameSync(tmp,file)}
test('stages, applies and rolls back a multi-file changeset',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-1',[{op:'write',path:'a.txt',content:'new\n'},{op:'write',path:'b.txt',content:'created\n'}]);assert.equal(cs.status,'STAGED');const applied=s.apply(cs.id);assert.equal(applied.status,'APPLIED');assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'new\n');assert.equal(fs.readFileSync(path.join(f.workspace,'b.txt'),'utf8'),'created\n');const rolled=s.rollback(cs.id);assert.equal(rolled.status,'ROLLED_BACK');assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n');assert.equal(fs.existsSync(path.join(f.workspace,'b.txt')),false)});
test('apply fails closed when preimage changed after staging',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-2',[{op:'write',path:'a.txt',content:'new'}]);fs.writeFileSync(path.join(f.workspace,'a.txt'),'human edit');assert.throws(()=>s.apply(cs.id),/APPLY_CONFLICT/)});
test('rollback refuses to overwrite a post-apply human edit',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-3',[{op:'write',path:'a.txt',content:'new'}]);s.apply(cs.id);fs.writeFileSync(path.join(f.workspace,'a.txt'),'human after apply');assert.throws(()=>s.rollback(cs.id),/ROLLBACK_CONFLICT/)});
test('apply preflights every path before mutating any file',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.writeFileSync(path.join(f.workspace,'b.txt'),'old-b\n');const cs=s.stage('run-test-4',[{op:'write',path:'a.txt',content:'new-a\n'},{op:'write',path:'b.txt',content:'new-b\n'}]);fs.writeFileSync(path.join(f.workspace,'b.txt'),'human-b\n');assert.throws(()=>s.apply(cs.id),/APPLY_CONFLICT:b\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n');assert.equal(fs.readFileSync(path.join(f.workspace,'b.txt'),'utf8'),'human-b\n');assert.equal(s.get(cs.id).status,'STAGED')});
test('rollback preflights every path before restoring any file',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.writeFileSync(path.join(f.workspace,'b.txt'),'old-b\n');const cs=s.stage('run-test-5',[{op:'write',path:'a.txt',content:'new-a\n'},{op:'write',path:'b.txt',content:'new-b\n'}]);s.apply(cs.id);fs.writeFileSync(path.join(f.workspace,'a.txt'),'human-a\n');assert.throws(()=>s.rollback(cs.id),/ROLLBACK_CONFLICT:a\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'human-a\n');assert.equal(fs.readFileSync(path.join(f.workspace,'b.txt'),'utf8'),'new-b\n');assert.equal(s.get(cs.id).status,'APPLIED')});
test('stage rejects multiple changes targeting one canonical workspace path',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);assert.throws(()=>s.stage('run-test-6',[{op:'write',path:'a.txt',content:'first\n'},{op:'write',path:'dir/../a.txt',content:'second\n'}]),/DUPLICATE_CHANGE_PATH:a\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n')});
test('stage rejects existing non-file targets before a partial apply can become possible',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.mkdirSync(path.join(f.workspace,'dir'));assert.throws(()=>s.stage('run-test-7',[{op:'write',path:'a.txt',content:'new-a\n'},{op:'delete',path:'dir'}]),/UNSUPPORTED_CHANGE_TARGET:dir/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n');assert.equal(fs.existsSync(path.join(f.workspace,'dir')),true);assert.equal(fs.readdirSync(path.join(f.runtime,'changesets')).length,0)});
test('stage rejects existing symlink targets instead of snapshotting only their referent bytes',t=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.writeFileSync(path.join(f.workspace,'target.txt'),'target-old\n');try{fs.symlinkSync('target.txt',path.join(f.workspace,'link.txt'))}catch(error){if(error?.code==='EPERM'||error?.code==='EACCES'){t.skip('symlink creation unavailable on this host');return}throw error}assert.throws(()=>s.stage('run-test-8',[{op:'write',path:'link.txt',content:'replacement\n'}]),/UNSUPPORTED_CHANGE_TARGET:link\.txt/);assert.equal(fs.lstatSync(path.join(f.workspace,'link.txt')).isSymbolicLink(),true);assert.equal(fs.readFileSync(path.join(f.workspace,'target.txt'),'utf8'),'target-old\n');assert.equal(fs.readdirSync(path.join(f.runtime,'changesets')).length,0)});
test('stage rejects a change whose existing ancestor is not a directory',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.writeFileSync(path.join(f.workspace,'dir'),'blocking-file\n');assert.throws(()=>s.stage('run-test-9',[{op:'write',path:'dir/child.txt',content:'child\n'}]),/UNSUPPORTED_CHANGE_ANCESTOR:dir\/child\.txt:dir/);assert.equal(fs.readdirSync(path.join(f.runtime,'changesets')).length,0)});
test('apply preflight rejects an ancestor that became non-directory before mutating earlier files',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-10',[{op:'write',path:'a.txt',content:'new-a\n'},{op:'write',path:'dir/child.txt',content:'child\n'}]);fs.writeFileSync(path.join(f.workspace,'dir'),'blocking-file\n');assert.throws(()=>s.apply(cs.id),/APPLY_CONFLICT:dir\/child\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n');assert.equal(s.get(cs.id).status,'STAGED')});
test('rollback preflight rejects an ancestor that became non-directory before restoring earlier files',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.mkdirSync(path.join(f.workspace,'dir'));fs.writeFileSync(path.join(f.workspace,'dir','child.txt'),'old-child\n');const cs=s.stage('run-test-11',[{op:'delete',path:'dir/child.txt'},{op:'write',path:'a.txt',content:'new-a\n'}]);s.apply(cs.id);fs.rmdirSync(path.join(f.workspace,'dir'));fs.writeFileSync(path.join(f.workspace,'dir'),'blocking-file\n');assert.throws(()=>s.rollback(cs.id),/ROLLBACK_CONFLICT:dir\/child\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'new-a\n');assert.equal(s.get(cs.id).status,'APPLIED')});
test('stage rejects an in-workspace symlink ancestor so path identity is not aliased',t=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);fs.mkdirSync(path.join(f.workspace,'target'));fs.writeFileSync(path.join(f.workspace,'target','child.txt'),'old-child\n');try{fs.symlinkSync('target',path.join(f.workspace,'alias'),'dir')}catch(error){if(error?.code==='EPERM'||error?.code==='EACCES'){t.skip('symlink creation unavailable on this host');return}throw error}assert.throws(()=>s.stage('run-test-12',[{op:'write',path:'alias/child.txt',content:'new-child\n'}]),/UNSUPPORTED_CHANGE_ANCESTOR:alias\/child\.txt:alias/);assert.equal(fs.readFileSync(path.join(f.workspace,'target','child.txt'),'utf8'),'old-child\n')});
test('apply rejects a same-content replacement object after staging',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-13',[{op:'write',path:'a.txt',content:'new\n'}]);assert.ok(cs.changes[0].before.identity);replaceSame(path.join(f.workspace,'a.txt'),'old\n');assert.throws(()=>s.apply(cs.id),/APPLY_CONFLICT:a\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'old\n');assert.equal(s.get(cs.id).status,'STAGED')});
test('rollback rejects a same-content replacement object after apply',()=>{const f=fixture(),s=new ChangesetStore(f.runtime,f.workspace);const cs=s.stage('run-test-14',[{op:'write',path:'a.txt',content:'new\n'}]);const applied=s.apply(cs.id);assert.ok(applied.applyReceipt.files[0].identity);replaceSame(path.join(f.workspace,'a.txt'),'new\n');assert.throws(()=>s.rollback(cs.id),/ROLLBACK_CONFLICT:a\.txt/);assert.equal(fs.readFileSync(path.join(f.workspace,'a.txt'),'utf8'),'new\n');assert.equal(s.get(cs.id).status,'APPLIED')});
