import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {ChangesetStore} from '../core/changesets.mjs';
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'twc-item-shape-'));const runtime=path.join(base,'runtime'),workspace=path.join(base,'workspace');fs.mkdirSync(runtime);fs.mkdirSync(workspace);return {base,runtime,workspace}}
function withStore(fn){const f=fixture();try{return fn(new ChangesetStore(f.runtime,f.workspace))}finally{fs.rmSync(f.base,{recursive:true,force:true})}}
function rewrite(store,staged,mutate){const f=store.file(staged.id);const doc=JSON.parse(fs.readFileSync(f,'utf8'));mutate(doc);fs.writeFileSync(f,JSON.stringify(doc));}
test('get rejects an unknown durable change operation',()=>withStore((store)=>{const staged=store.stage('run-item-shape',[{op:'write',path:'src/value.mjs',content:'x\n'}]);rewrite(store,staged,doc=>{doc.changes[0].op='copy'});assert.throws(()=>store.get(staged.id),e=>e?.message==='INVALID_CHANGESET_CHANGE_SHAPE')}));
test('get rejects malformed durable before-image shape',()=>withStore((store)=>{const staged=store.stage('run-item-shape',[{op:'write',path:'src/value.mjs',content:'x\n'}]);rewrite(store,staged,doc=>{doc.changes[0].before.exists='false'});assert.throws(()=>store.get(staged.id),e=>e?.message==='INVALID_CHANGESET_CHANGE_SHAPE')}));
test('get rejects malformed durable after-image hash shape',()=>withStore((store)=>{const staged=store.stage('run-item-shape',[{op:'write',path:'src/value.mjs',content:'x\n'}]);rewrite(store,staged,doc=>{doc.changes[0].after.sha256='not-a-sha256'});assert.throws(()=>store.get(staged.id),e=>e?.message==='INVALID_CHANGESET_CHANGE_SHAPE')}));
test('get rejects negative durable image sizes',()=>withStore((store)=>{const staged=store.stage('run-item-shape',[{op:'write',path:'src/value.mjs',content:'x\n'}]);rewrite(store,staged,doc=>{doc.changes[0].after.size=-1});assert.throws(()=>store.get(staged.id),e=>e?.message==='INVALID_CHANGESET_CHANGE_SHAPE')}));
test('a store-emitted durable change remains readable',()=>withStore((store)=>{const staged=store.stage('run-item-shape',[{op:'write',path:'src/value.mjs',content:'x\n'}]);assert.equal(store.get(staged.id).changes[0].op,'write')}));
