import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {TaskStore} from '../core/tasks.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const bridge=path.resolve(here,'../bridge/dwac_bridge.py');
function write(file,content){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content)}
function fakeDwac({fourMode=true}={}){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'twc-four-mode-dwac-'));const pkg=path.join(root,'structural_generation','dwac_structural');
 write(path.join(pkg,'software_production_pipeline.py'),`class Stage:\n def __init__(self,i): self.stage_id=f's{i}'\nclass Plan:\n plan_id='plan-x'\n stages=[Stage(i) for i in range(12)]\n def topological_order(self): return [x.stage_id for x in self.stages]\nclass SoftwareProductionPipelineCompiler:\n def compile(self,prompt,profile='application'): return Plan()\n`);
 write(path.join(pkg,'aaa_game_factory.py'),`class AAAGameFactoryCompiler:\n def compile(self,prompt): raise RuntimeError('not used')\n`);
 write(path.join(pkg,'north_star_self_development.py'),`from dataclasses import dataclass\nfrom enum import Enum\nclass DevelopmentMode(str,Enum): WHOLE_ARTIFACT='WHOLE_ARTIFACT'; DEEP_DEVELOPMENT='DEEP_DEVELOPMENT'\nclass Gate(str,Enum): AUTONOMOUS='AUTONOMOUS'\n@dataclass\nclass NorthStarSpec: goal:str\n@dataclass\nclass Observation:\n observation_id:str; domain:str; signal:str; severity:float; centrality:float; recurrence:float; evidence:tuple=()\n @property\n def pressure(self): return self.severity*.45+self.centrality*.35+self.recurrence*.20\n@dataclass\nclass BottleneckCandidate:\n candidate_id:str; domain:str; problem:str; expected_goal_gain:float; reuse_gain:float; autonomy_gain:float; evidence_gain:float; implementation_cost:float; regression_risk:float\n @property\n def score(self): return self.expected_goal_gain*.32+self.reuse_gain*.14+self.autonomy_gain*.28+self.evidence_gain*.16-self.implementation_cost*.06-self.regression_risk*.04\nclass D: pass\nclass NorthStarSelfDevelopmentController:\n def __init__(self,spec): self.spec=spec\n def diagnose(self,signals,candidates):\n  ranked=tuple(sorted(candidates,key=lambda x:x.score,reverse=True));d=D();d.selected=ranked[0];d.mode=DevelopmentMode.WHOLE_ARTIFACT;d.reason='native';d.sovereignty_gate=Gate.AUTONOMOUS;d.cycle_id='NSC-test';d.ranked_candidates=ranked;d.portfolio=ranked[:3];return d\n`);
 if(fourMode)write(path.join(pkg,'four_mode_router.py'),`from dataclasses import dataclass\nfrom enum import Enum\nclass FourDevelopmentMode(str,Enum):\n WHOLE_ARTIFACT='WHOLE_ARTIFACT';DEEP_DEVELOPMENT='DEEP_DEVELOPMENT';NORTH_STAR='NORTH_STAR';NORTH_STAR_BURST='NORTH_STAR_BURST'\n@dataclass(frozen=True)\nclass FourModeSignal:\n breadth:float=0.;bottleneck_centrality:float=0.;evidence_density:float=0.;adjacent_work_count:int=0;direction_stability:float=0.;urgency:float=0.;artifact_pressure:float=0.\n@dataclass(frozen=True)\nclass Decision: mode:FourDevelopmentMode;reason:str;scores:dict\nclass FourDevelopmentModeRouter:\n def route(self,s):\n  scores={'WHOLE_ARTIFACT':.45*s.breadth+.35*s.artifact_pressure+.2*(1-s.bottleneck_centrality),'DEEP_DEVELOPMENT':.55*s.bottleneck_centrality+.3*s.evidence_density+.15*(1-s.breadth),'NORTH_STAR':.55*s.direction_stability+.25*s.evidence_density+.2*(1-s.urgency),'NORTH_STAR_BURST':.35*s.direction_stability+.25*s.evidence_density+.2*s.urgency+.2*min(1,s.adjacent_work_count/8)}\n  if s.breadth>=.8 and s.artifact_pressure>=.7:m=FourDevelopmentMode.WHOLE_ARTIFACT\n  elif s.bottleneck_centrality>=.85 and s.evidence_density>=.7:m=FourDevelopmentMode.DEEP_DEVELOPMENT\n  elif s.direction_stability>=.8 and s.adjacent_work_count>=4 and s.urgency>=.5:m=FourDevelopmentMode.NORTH_STAR_BURST\n  else:\n   if s.adjacent_work_count<2:scores['NORTH_STAR_BURST']*=.35\n   m=FourDevelopmentMode(max(scores,key=scores.get))\n  return Decision(m,'routed',scores)\n`);
 return root;
}
function invoke(root){const workspace=fs.mkdtempSync(path.join(os.tmpdir(),'twc-four-mode-ws-'));fs.mkdirSync(path.join(workspace,'.git'));const r=spawnSync(process.env.PYTHON||'python',[bridge,'--dwac-root',root,'--workspace',workspace,'--prompt','build app'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr||r.stdout);return JSON.parse(r.stdout)}
test('TaskStore has one routed development phase instead of a fixed mode sequence',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'twc-four-mode-tasks-'));const store=new TaskStore(dir);const tasks=store.plan('goal',{mode:'NORTH_STAR_BURST',runId:'r1'});assert.deepEqual(tasks.map(x=>x.phase),['observe','develop','apply','validate','repair','review','delivery']);assert.equal(tasks.find(x=>x.phase==='develop').mode,'NORTH_STAR_BURST');assert.match(tasks.find(x=>x.phase==='develop').title,/北极星爆发/)});
test('DWAC bridge consumes the upstream four-mode router and preserves native mode evidence',()=>{const out=invoke(fakeDwac({fourMode:true}));assert.equal(out.routing_source,'DWAC_FOUR_MODE_ROUTER');assert.equal(out.native_mode,'WHOLE_ARTIFACT');assert.ok(['NORTH_STAR','NORTH_STAR_BURST','WHOLE_ARTIFACT','DEEP_DEVELOPMENT'].includes(out.mode));assert.equal(Object.keys(out.route_scores).length,4);assert.ok(out.route_signal)});
test('DWAC bridge falls back honestly when four-mode router is unavailable',()=>{const out=invoke(fakeDwac({fourMode:false}));assert.equal(out.routing_source,'NORTH_STAR_NATIVE_FALLBACK');assert.equal(out.mode,out.native_mode);assert.equal(out.route_signal,null)});
